name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  macos:
    runs-on: macos-latest

    strategy:
      matrix:
        include:
          - build: 'metal'
            defines: '-DLLAMA_NATIVE=OFF -DLLAMA_FAST=ON -DLLAMA_BUILD_SERVER=ON -DBUILD_SHARED_LIBS=ON'
          # - build: 'nometal'
          #   defines: '-DLLAMA_NATIVE=OFF -DLLAMA_FAST=ON -DLLAMA_BUILD_SERVER=ON -DBUILD_SHARED_LIBS=ON -DLLAMA_NO_METAL=1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ggerganov/llama.cpp

      - name: Compile with cmake.
        run: |
          mkdir build
          cd build
          cmake .. ${{ matrix.defines }}
          cmake --build . --config Release

      - name: Import apple code signing certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          keychain: build
          p12-file-base64: ${{ secrets.OSX_P12_FILE }}
          p12-password: ${{ secrets.OSX_CERT_PASSWORD }}

      - name: Sign OSX Binaries
        run: |
          security unlock-keychain -p ${{ secrets.OSX_CERT_PASSWORD }} build.keychain
          for binary in build/bin/*; do
            if [ -f "$binary" ]; then
              echo "Signing $binary"
              codesign --keychain build.keychain --sign "Developer ID Application: Jesse Noller" --timestamp --options runtime "$binary"
            fi
          done
        shell: bash

      - name: Pack Artifacts
        run: |
          cd build
          mkdir macos-universal-${{ matrix.build }}
          cp -R bin/* macos-universal-${{ matrix.build }}
          ln -s macos-universal-${{ matrix.build }}/main macos-universal-${{ matrix.build }}/llamacpp
          tar -czvf macos-${{ matrix.build }}.tar.gz macos-${{ matrix.build }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.build }}
          path: |
            build/macos-${{ matrix.build }}.tar.gz
  
  release:
    needs: macos
    runs-on: macos-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          name: Release ${{ github.run_number }}
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # windows-cpu-only:
  #   runs-on: windows-latest

  #   strategy:
  #     matrix:
  #       include:
  #         - build: 'noavx'
  #           defines: '-DLLAMA_NATIVE=OFF -DLLAMA_FAST=ON -DLLAMA_BUILD_SERVER=ON -DLLAMA_AVX=OFF -DLLAMA_AVX2=OFF -DLLAMA_FMA=OFF -DBUILD_SHARED_LIBS=ON'
  #         - build: 'avx2'
  #           defines: '-DLLAMA_NATIVE=OFF -DLLAMA_FAST=ON -DLLAMA_BUILD_SERVER=ON -DBUILD_SHARED_LIBS=ON'
  #         - build: 'avx'
  #           defines: '-DLLAMA_NATIVE=OFF -DLLAMA_FAST=ON -DLLAMA_BUILD_SERVER=ON -DLLAMA_AVX2=OFF -DBUILD_SHARED_LIBS=ON'
  #         - build: 'avx512'
  #           defines: '-DLLAMA_NATIVE=OFF -DLLAMA_FAST=ON -DLLAMA_BUILD_SERVER=ON -DLLAMA_AVX512=ON -DBUILD_SHARED_LIBS=ON'
  
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         repository: ggerganov/llama.cpp

  #     - name: Compile with cmake.
  #       run: |
  #         mkdir build
  #         cd build
  #         cmake .. ${{ matrix.defines }}
  #         cmake --build . --config Release

  #     - name: Pack Artifacts
  #       run: |
  #         cd build/bin
  #         ls Release

  # windows-cuda:
  #   runs-on: windows-latest

  #   strategy:
  #     matrix:
  #       include:
  #         - build: 'cublas'
  #           defines: '-DLLAMA_NATIVE=OFF -DLLAMA_FAST=ON -DLLAMA_BUILD_SERVER=ON -DLLAMA_CUBLAS=ON -DBUILD_SHARED_LIBS=ON'

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         repository: ggerganov/llama.cpp

  #     - name: Install CUDA
  #       uses: Jimver/cuda-toolkit@v0.2.11
  #       id: cuda-toolkit
  #       with:
  #         cuda: '12.2.0'
  #         method: 'network'
  #         sub-packages: '["nvcc", "cudart", "cublas", "cublas_dev", "thrust", "visual_studio_integration"]'

  #     - name: Compile with cmake.
  #       run: |
  #         mkdir build
  #         cd build
  #         cmake .. ${{ matrix.defines }}
  #         cmake --build . --config Release

  #     - name: Pack Artifacts
  #       run: |
  #         cd build/bin
  #         ls Release